CODE_OF_CONDUCT.md, CONTRIBUTING.md
Adding CODE_OF_CONDUCT.md, CONTRIBUTING.md and CONTRIBUTORS.md files
=> docs: add CODE_OF_CONDUCT.md, CONTRIBUTING.md and CONTRIBUTORS.md files

app/price_calculator.py, app/seed_data.py, cdk/bedrock_limits_small.csv, core/inference/bedrock/bedrock_inferencer.py
Support of Adding Amazon Nova models
=> feat: support for nova models

ui/app/composables/projects.ts, ui/app/pages/projects/[id]/validexperiments.vue
1. Polling for valid experiments for every 10 seconds until we get all the valid experiments
=> Feat: Added Polling for fetching valid experiments on demand

ui/app/components/Project/List.vue
1. Sorting feature added to all columns in project table
2. Removed hyperlink to project name field
=> fix: added sorting to all columns to project table

ui/app/components/Breadcumb.vue, ui/app/pages/projects/[id]/execute.vue, ui/app/pages/projects/[id]/experiments/[experimentId].vue, ui/app/pages/projects/[id]/index.vue, ui/app/pages/projects/[id]/validexperiments.vue, ui/app/pages/projects/create.vue, ui/app/pages/projects/index.vue, ui/shared/types/breadcumb.type.ts
1. Breadcumb component has been created and added to all pages
=> feat: Added a dynamic breadcumb to all pages

ui/app/components/Breadcumb.vue, ui/app/components/Project/Experiment/List.vue, ui/app/components/Project/Experiment/ValidList.vue, ui/app/components/Project/List.vue, ui/app/layouts/default.vue, ui/app/pages/projects/[id]/experiments/[experimentId].vue
1. made page level header part sticky
2. made all table headers sticky
3. Added space to valid experiments key in breadcumb
=> feat: Added sticky header to tables and page

ui/app/composables/shared.ts
bedrock_us prefix added in nova model retrievalStrategy value
=> chore: bedrock_us prefix added on nova model

ui/app/components/Project/Create/DataStrategyStep.vue
fix: removed disable button condition on data strategy form
=> fix: removed disable button condition on data strategy form

ui/app/components/Project/Experiment/DetailsButton.vue, ui/app/components/Project/Experiment/ValidList.vue
Bug related to Hierarchical chuck percentage is not getting updated in valid experiments page and details page is fixed
=> fix: Hierarchical chuck percentage is not getting updated in valid experiments page and details page

cdk/state_machine/state_machine_stack.py
BugFix:
RuntimeError: Error: Cannot add to chain: last state in chain (Evaluate Chunking Strategy) does not allow it
=> fixing runtime error caused by adding new choice

ui/app/components/Project/Experiment/ValidList.vue
fix : Updated chunk overlap column label in valid experiiments page
=> fix : Updated chunk overlap column label in valid experiiments page

ui/app/composables/shared.ts
- Added new Sagemaker models in the UI
- Added new vector dimension option
=> feat(ui): added sagemaker ui options

ui/app/components/PromptGuideSelect.vue, ui/shared/types/projects.type.ts
fix: prompt file field validation added, mismatch validation errors corrected
=> fix: prompt file field validation added, mismatch validation errors corrected

ui/app/components/Project/Create/EvalStrategyStep.vue, ui/app/components/Project/Create/Form.vue, ui/app/composables/projects.ts, ui/app/composables/shared.ts, ui/app/composables/tooltip.ts, ui/shared/types/projects.type.ts
feature: guardrails selection feature has been added to EvalStrategy form
=> feature: guardrails selection feature has been added to EvalStrategy form

ui/app/components/Project/Create/EvalStrategyStep.vue, ui/app/components/Project/Create/IndexingStrategyStep.vue
fix: add chunkin glabels to fixed, hierarchical and added percentage to labels
=> fix: add chunkin glabels to fixed, hierarchical and added percentage to labels

ui/app/components/Project/Create/Form.vue, ui/app/components/Project/Experiment/List.vue, ui/app/components/Project/Experiment/ValidList.vue
- Changed Evaluation strategy json structure.
=> chore: changed the request payload structure for evaluation step

ui/app/components/Project/Experiment/Assessments.vue, ui/app/pages/projects/[id]/experiments/[experimentId].vue
[Feat/show question metrics guardrails UI](feat: added question metrics columns for guardrails in experiment details page)
=> feat: added question metrics columns for guardrails in experiment details page

cdk/state_machine/state_machine_stack.py
=> feature : changes to state machine to support evaluation strategy selection

ui/app/components/Project/Experiment/DetailsButton.vue, ui/app/pages/projects/[id]/experiments/[experimentId].vue, ui/shared/types/projects.type.ts
1. prefixed with guardrails in assessment column in experiment details page
2. added guardrails information to details modal in experiment details page
3. added form validation upon selecting chunking strategy as fixed and hierarchical strategies.
=> fix: chunking selection form validtion added, guardrails details added in details page

ui/app/components/Project/Create/EvalStrategyStep.vue, ui/app/components/Project/Create/Form.vue, ui/app/components/Project/Create/IndexingStrategyStep.vue, ui/app/components/Project/Create/RetrievalStrategyStep.vue, ui/app/components/Project/Experiment/DetailsButton.vue, ui/app/components/Project/Experiment/DirectionalPricing.vue, ui/app/components/Project/Experiment/List.vue, ui/app/components/Project/Experiment/ValidList.vue, ui/app/composables/shared.ts, ui/app/pages/projects/[id]/experiments/[experimentId].vue, ui/shared/types/projects.type.ts
1. tabs added in experiments details page
2. cost breakdown tab , details tab added
3. showing directional pricing in modal
4. other create project related ui bugs fixed
=> feat: tabs added in experiment details page and other bug fixes

ui/app/components/Project/Create/EvalStrategyStep.vue, ui/app/components/Project/Create/IndexingStrategyStep.vue, ui/app/components/Project/Experiment/DetailsButton.vue, ui/app/components/Project/Experiment/DirectionalPricing.vue, ui/app/components/Project/Experiment/ValidList.vue, ui/app/composables/shared.ts, ui/app/composables/tooltip.ts, ui/app/pages/projects/[id].vue, ui/app/pages/projects/[id]/experiments/[experimentId].vue
1. updated breakdown tab
2. add sagemaker related info in headup part for expriment details page
3. guardrail ui related changes
4. directional pricing related changes
5. other bug fixes
=> fix: cosmotic and other ui changes done for v1.1.0 release

app/routes/bedrock_config.py, util/bedrock_utils.py
- knowledge base API now expects a region
- Added status ACTIVE check while listing knowledge base
- Will only list knowledge bases with at least one data source in ACTIVE state
- Removed listing documents as it will fail for crawled data source knowledge bases
=> fix: API fails for crawled datasource kbs

app/configuration_validation.py, app/routes/execution.py, baseclasses/base_classes.py
```[
{
"knowledge_base": true,
"bedrock_knowledge_base": true,
"region": "us-east-1",
"kb_data": "GXFOQF1TUB",
"chunking_strategy": "",
"vector_dimension": 0,
"chunk_size": 0,
"chunk_overlap": 0,
"indexing_algorithm": "",
"knn_num": 3,
"temp_retrieval_llm": 0.1,
"rerank_model_id": "none",
"n_shot_prompts": 0,
"gateway_enabled": true,
"gateway_api_key": "",
"gateway_url": "",
"enable_guardrails": false,
"guardrail_id": "",
"guardrail_name": "",
"guardrail_version": "",
"enable_prompt_guardrails": false,
"enable_context_guardrails": false,
"enable_response_guardrails": false,
"kb_name": "sec10q-non-graphrag",
"flotorch_kb_id": 1,
"embedding_service": "",
"embedding_model": "",
"retrieval_service": "",
"retrieval_model": "config/bedrock-config",
"eval_service": "ragas", …
```
=> [Review] change for supporting the llm kb data
